export const Tags = [
    "JavaScript",
    "Typescript",
    "MERN",
    "DRF",
    "DJango",
    "FastAPI",
    "React",
    "React.js",
    "Node.js",
    "Python",
    "AI",
    "Ruby",
    "Java",
    "AWS",
    "CSS",
    "TailwindCSS",
    "ShadCN",
    "HTML",
    "Web3",
    "Solidity",
    "Ethereum",
    "Blockchain",
    "Smart Contracts",
    "NFT",
    "Metaverse",
    "DApps",
    "DeFi",
    "REST",
    "GraphQL",
    "Kafka",
    "RabbitMQ",
    "Microservices",
    "SaaS",
    "Machine Learning",
    "Deep Learning",
    "Neural Networks",
    "NLP",
    "Computer Vision",
    "Data Science",
    "TensorFlow",
    "PyTorch",
    "Reinforcement Learning",
    "Cybersecurity",
    "Ethical Hacking",
    "Penetration Testing",
    "Network Security",
    "Cryptography",
    "SQL",
    "NoSQL",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "Data Structures",
    "Algorithms",
    "Operating Systems",
    "Distributed Systems",
    "Automata",
    "Concurrency",
    "Design Patterns",
    "Angular",
    "Vue.js",
    "Svelte",
    "PHP",
    "Laravel",
    "Django",
    "Ruby on Rails",
    "ASP.NET",
    "Bootstrap",
    "jQuery",
    "Scikit-learn",
    "OpenCV",
    "RPA",
    "Predictive Analytics",
    "AI Ethics",
    "ChatGPT",
    "GPT-4",
    "Recommender Systems",
    "Data Mining",
    "Big Data",
    "OS",
    "Linux",
    "MacOS",
    "UNIX",
    "System Design",
    "Architecture",
    "DevOps",
    "Cloud Computing",
    "Docker",
    "Kubernetes",
    "Git",
    "Github",
    "Pipelines",
    "Automation",
    "CI/CD",
    "Jenkins",
    "Github Actions",
    "Gitlab",
    "Linode",
    "Jest"
];  